[[redirects]]
  from = "/success"
  to = "/success/index.html"
  status = 200

[[redirects]]
  from = "/success/"
  to = "/success/index.html"
  status = 200

# Fallback SPA (mantenha por último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
